[package]
name = "va-voice"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.17.1"
serde_json = "1.0.120"
vosk = "0.3.1"
dotenvy = "0.15.7"
reqwest = { version = "0.13.1", features = ["blocking", "json"] }
tracing = "0.1.44"
